### ISSUE TITLE
[DOC] settings.jsdoc.tagNamePreference

### ISSUE THREAD

**Issue by TriMoon** [gajus/eslint-plugin-jsdoc#367]
I had a hard time to override the setting that prefers `@augments` over `@extends` that is enabled by the default rules.
Reading [Alias Preference](https://github.com/gajus/eslint-plugin-jsdoc#alias-preference), there is no mention that you need to override the default setting, and do this instead: `.eslint.yml`
```yaml
---
    settings:
        jsdoc:
            tagNamePreference:
                extends: extends
                augments:
                    message: "@extends is to be used over @augments in Javascript classes."
                    replacement: extends
                method: method
                function:
                    message: "@method is to be used over @function in Javascript classes."
                    replacement: method
```
- Note the `extends: extends`...
This happend with my current version: `eslint-plugin-jsdoc@15.8.0`
